name: Deploy to Production
on:
  push:
    branches: [main]
jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Staging
        id: deploy-vercel-staging
        uses: amondnet/vercel-action@v20
        if : github.event_name == 'push' && github.ref == 'refs/heads/staging'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}

      - name: Deploy to Production
        id: deploy-vercel-production
        uses: amondnet/vercel-action@v20
        if : github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}